const router = require("express").Router();
const controller = require("../controllers/postController");
const validator = require("../middleware/validate");
const auth = require("../middleware/auth");
const { validate } = require("../models/postModel");
router.get("/hot", controller.getTrending);
router.get("/:id", controller.getOne);
router.get("/", controller.getAll);
router.use(auth.protect);
router.post("/comment/:id", controller.reply);
router.post("/", validator(validate), controller.addOne);
router.put("/like/:id", controller.likeOne);
router.put("/dislike/:id", controller.dislikeOne);
module.exports = router;
